### ISSUE TITLE
Nice work

### ISSUE THREAD

**Issue by JUGGHM** [hukkai/rescaling#1]
This is not a issue but I could not help commenting here for respecting this awesome work. The philosophy of this work might play an important role in my ongoing work.

**Comment by hukkai** [comment]
Thanks for reading our paper! We are working on an extended journal version with more comparison on normalization/non-normalization network and discussion on networks without skip connections (A manuscript can be found at https://github.com/hukkai/no-residual-network, final version coming soon). It is our pleasure if we can provide any insights on your work!
